# Generated by Django 4.2.27 on 2026-03-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit_name', models.CharField(help_text='Unit name (e.g., Kilogram)', max_length=100)),
                ('short_name', models.CharField(help_text='Short name (e.g., kg)', max_length=50)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('branch', models.ForeignKey(blank=True, help_text='Associated branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_units', to='company.branch')),
                ('company', models.ForeignKey(help_text='Associated company', on_delete=django.db.models.deletion.CASCADE, related_name='item_units', to='company.company')),
            ],
            options={
                'verbose_name': 'Item Unit',
                'verbose_name_plural': 'Item Units',
                'db_table': 'item_units',
                'ordering': ['unit_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category_name', models.CharField(help_text='Category name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('branch', models.ForeignKey(blank=True, help_text='Associated branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='company.branch')),
                ('company', models.ForeignKey(help_text='Associated company', on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='company.company')),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'db_table': 'item_categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item_code', models.CharField(help_text='Unique item code/SKU', max_length=50)),
                ('item_images', models.JSONField(blank=True, default=list, help_text='List of images with metadata (url, sort_order, is_primary)')),
                ('item_name', models.CharField(help_text='Item name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Item description', null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price', max_digits=12, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=12)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0.0, help_text='Opening stock', max_digits=12)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, help_text='Current stock', max_digits=12)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum stock level', max_digits=12)),
                ('item_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight per unit', max_digits=10, null=True)),
                ('barcode', models.CharField(blank=True, help_text='Barcode', max_length=50, null=True, unique=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('branch', models.ForeignKey(blank=True, help_text='Associated branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='company.branch')),
                ('brand', models.ForeignKey(blank=True, help_text='Brand name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='settings.brand')),
                ('category', models.ForeignKey(blank=True, help_text='Item category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.itemcategory')),
                ('company', models.ForeignKey(help_text='Associated company', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='company.company')),
                ('primary_unit', models.ForeignKey(help_text='Primary unit of measurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_primary', to='items.itemunit')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'items',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('movement_type', models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE', 'Purchase'), ('SALES_RETURN', 'Sales Return'), ('TRANSFER_IN', 'Transfer In'), ('ADJUSTMENT_IN', 'Adjustment In'), ('SALE', 'Sale'), ('PURCHASE_RETURN', 'Purchase Return'), ('TRANSFER_OUT', 'Transfer Out'), ('DAMAGE', 'Damage'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('SAMPLE_GIVEN', 'Sample Given'), ('INTERNAL_USE', 'Internal Use'), ('THEFT_LOSS', 'Theft / Loss'), ('DAMAGE_EXPIRED', 'Damage / Expired')], max_length=30)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Moved quantity', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Stock after movement', max_digits=12)),
                ('reference_type', models.CharField(blank=True, help_text='Source document type', max_length=50, null=True)),
                ('reference_id', models.IntegerField(blank=True, help_text='Source document ID', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='company.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='items.item')),
            ],
            options={
                'verbose_name': 'Stock Ledger',
                'verbose_name_plural': 'Stock Ledger',
                'db_table': 'stock_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'branch', 'item', 'created_at'], name='stock_ledge_company_5c5697_idx'), models.Index(fields=['movement_type', 'created_at'], name='stock_ledge_movemen_0af00e_idx'), models.Index(fields=['reference_type', 'reference_id'], name='stock_ledge_referen_f43b64_idx'), models.Index(fields=['status'], name='stock_ledge_status_435f09_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='itemunit',
            index=models.Index(fields=['company', 'branch', 'unit_name'], name='item_units_company_462ada_idx'),
        ),
        migrations.AddIndex(
            model_name='itemunit',
            index=models.Index(fields=['status'], name='item_units_status_b6d0ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemunit',
            unique_together={('company', 'branch', 'unit_name')},
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['company', 'branch', 'category_name'], name='item_catego_company_99f6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['status'], name='item_catego_status_5f22d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.CheckConstraint(check=models.Q(('category_name', ''), _negated=True), name='category_name_not_empty'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('company', 'branch', 'category_name')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company', 'branch', 'item_code'], name='items_company_d63af2_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company', 'branch', 'item_name'], name='items_company_645a94_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='items_status_bc9bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company', 'branch', 'brand'], name='items_company_1c18e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('company', 'branch', 'item_name'), ('company', 'branch', 'barcode'), ('company', 'branch', 'item_code')},
        ),
    ]
