# Generated by Django 4.2.26 on 2026-02-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0005_alter_shop_city_alter_shop_country_alter_shop_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item_code', models.CharField(help_text='Unique item code/SKU', max_length=50)),
                ('item_image', models.ImageField(blank=True, help_text='Item image', null=True, upload_to='item_image')),
                ('item_images', models.JSONField(blank=True, default=list, help_text='List of item images with metadata')),
                ('item_name', models.CharField(help_text='Item name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Item description', null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase price', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price', max_digits=12)),
                ('hsn_code', models.CharField(blank=True, help_text='HSN/SAC code', max_length=20, null=True)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0.0, help_text='Opening stock', max_digits=12)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, help_text='Current stock', max_digits=12)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum stock level', max_digits=12)),
                ('max_stock_level', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum stock level', max_digits=12)),
                ('item_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight per unit', max_digits=10, null=True)),
                ('barcode', models.CharField(blank=True, help_text='Barcode', max_length=50, null=True, unique=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'items',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit_name', models.CharField(help_text='Unit name (e.g., Kilogram)', max_length=100)),
                ('short_name', models.CharField(help_text='Short name (e.g., kg)', max_length=50)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('shop', models.ForeignKey(help_text='Associated shop', on_delete=django.db.models.deletion.CASCADE, related_name='item_units', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Item Unit',
                'verbose_name_plural': 'Item Units',
                'db_table': 'item_units',
                'ordering': ['unit_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category_name', models.CharField(help_text='Category name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('shop', models.ForeignKey(help_text='Associated shop', on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'db_table': 'item_categories',
                'ordering': ['category_name'],
            },
        ),
    ]
