# Generated by Django 4.2.26 on 2026-02-03 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0005_alter_shop_city_alter_shop_country_alter_shop_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Unit name (e.g., Kilogram)', max_length=100)),
                ('short_name', models.CharField(help_text='Short name (e.g., kg)', max_length=50)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('shop', models.ForeignKey(help_text='Associated shop', on_delete=django.db.models.deletion.CASCADE, related_name='item_units', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Item Unit',
                'verbose_name_plural': 'Item Units',
                'db_table': 'item_units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Category name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('shop', models.ForeignKey(help_text='Associated shop', on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'db_table': 'item_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item_code', models.CharField(help_text='Unique item code/SKU', max_length=50, unique=True)),
                ('item_image', models.ImageField(blank=True, help_text='Item image', null=True, upload_to='item_image')),
                ('item_name', models.CharField(help_text='Item name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Item description', null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase price', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price', max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate', max_digits=5)),
                ('hsn_code', models.CharField(blank=True, help_text='HSN/SAC code', max_length=20, null=True)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0.0, help_text='Opening stock', max_digits=12)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, help_text='Current stock', max_digits=12)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum stock level', max_digits=12)),
                ('max_stock_level', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum stock level', max_digits=12)),
                ('item_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight per unit', max_digits=10, null=True)),
                ('brand', models.CharField(blank=True, help_text='Brand name', max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, help_text='Barcode', max_length=50, null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('category', models.ForeignKey(blank=True, help_text='Item category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.itemcategory')),
                ('primary_unit', models.ForeignKey(help_text='Primary unit of measurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_primary', to='items.itemunit')),
                ('shop', models.ForeignKey(help_text='Associated shop', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'items',
                'ordering': ['item_name'],
            },
        ),
        migrations.AddIndex(
            model_name='itemunit',
            index=models.Index(fields=['shop', 'name'], name='item_units_shop_id_59dd45_idx'),
        ),
        migrations.AddIndex(
            model_name='itemunit',
            index=models.Index(fields=['status'], name='item_units_status_b6d0ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemunit',
            unique_together={('shop', 'name')},
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['shop', 'name'], name='item_catego_shop_id_07b019_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['status'], name='item_catego_status_5f22d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('shop', 'name')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['shop', 'item_code'], name='items_shop_id_4e953e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['shop', 'item_name'], name='items_shop_id_978c20_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='items_status_bc9bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['brand'], name='items_brand_8f2790_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('shop', 'item_code')},
        ),
    ]
