# Generated by Django 4.2.26 on 2026-02-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE items DROP FOREIGN KEY items_tax_fk_id_4b2f934c_fk_taxes_id;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "ALTER TABLE items DROP COLUMN tax_fk_id;",
            reverse_sql="ALTER TABLE items ADD COLUMN tax_fk_id INT(11) NULL;"
        ),
    ]
