# Generated by Django 4.2.26 on 2026-03-08 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('shops', '0005_alter_shop_city_alter_shop_country_alter_shop_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('movement_type', models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('NEW_STOCK', 'New Stock'), ('SALE_STOCK', 'Sale Stock'), ('RETURN_STOCK', 'Return Stock'), ('DAMAGED_STOCK', 'Damaged Stock'), ('USED_STOCK', 'Used Stock'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out')], max_length=30)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Moved quantity', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Stock after movement', max_digits=12)),
                ('reference_type', models.CharField(blank=True, help_text='Source document type', max_length=50, null=True)),
                ('reference_id', models.IntegerField(blank=True, help_text='Source document ID', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='items.item')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Stock Ledger',
                'verbose_name_plural': 'Stock Ledger',
                'db_table': 'stock_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['shop', 'item', 'created_at'], name='stock_ledge_shop_id_0ebdbc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['movement_type', 'created_at'], name='stock_ledge_movemen_88fc32_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_ledge_referen_a43814_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['status'], name='stock_ledge_status_60333a_idx'),
        ),
    ]
