# Generated by Django 4.2.26 on 2026-02-22 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='settings.brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Tax rate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax', to='settings.tax'),
        ),
    ]
