# Generated by Django 4.2.26 on 2026-01-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted'),
        ),
    ]
