# Generated by Django 4.2.26 on 2026-02-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0005_alter_shop_city_alter_shop_country_alter_shop_state'),
        ('settings', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='settings.brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Item category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.itemcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='primary_unit',
            field=models.ForeignKey(help_text='Primary unit of measurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_primary', to='items.itemunit'),
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(help_text='Associated shop', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Tax rate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='settings.tax'),
        ),
        migrations.AddIndex(
            model_name='itemunit',
            index=models.Index(fields=['shop', 'unit_name'], name='item_units_shop_id_365931_idx'),
        ),
        migrations.AddIndex(
            model_name='itemunit',
            index=models.Index(fields=['status'], name='item_units_status_b6d0ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemunit',
            unique_together={('shop', 'unit_name')},
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['shop', 'category_name'], name='item_catego_shop_id_345c51_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['status'], name='item_catego_status_5f22d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.CheckConstraint(check=models.Q(('category_name', ''), _negated=True), name='category_name_not_empty'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('shop', 'category_name')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['shop', 'item_code'], name='items_shop_id_4e953e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['shop', 'item_name'], name='items_shop_id_978c20_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='items_status_bc9bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['brand'], name='items_brand_i_8ca26d_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tax'], name='items_tax_id_42fc41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('shop', 'item_name'), ('shop', 'barcode'), ('shop', 'item_code')},
        ),
    ]
