# Generated by Django 4.2.26 on 2026-02-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_shop_city_alter_shop_country_alter_shop_state'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('shop', 'item_code')},
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(help_text='Unique item code/SKU', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('shop', 'item_code'), ('shop', 'barcode'), ('shop', 'item_name')},
        ),
    ]
