# Generated by Django 4.2.26 on 2026-03-30 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('items', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='settings.brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Item category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.itemcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(help_text='Associated company', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='company.company'),
        ),
        migrations.AddField(
            model_name='item',
            name='primary_unit',
            field=models.ForeignKey(help_text='Primary unit of measurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_primary', to='items.itemunit'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['company', 'branch', 'item', 'created_at'], name='stock_ledge_company_5c5697_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['movement_type', 'created_at'], name='stock_ledge_movemen_0af00e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_ledge_referen_f43b64_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['status'], name='stock_ledge_status_435f09_idx'),
        ),
        migrations.AddIndex(
            model_name='itemunit',
            index=models.Index(fields=['company', 'branch', 'unit_name'], name='item_units_company_462ada_idx'),
        ),
        migrations.AddIndex(
            model_name='itemunit',
            index=models.Index(fields=['status'], name='item_units_status_b6d0ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemunit',
            unique_together={('company', 'branch', 'unit_name')},
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['company', 'branch', 'category_name'], name='item_catego_company_99f6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['status'], name='item_catego_status_5f22d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.CheckConstraint(check=models.Q(('category_name', ''), _negated=True), name='category_name_not_empty'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('company', 'branch', 'category_name')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company', 'branch', 'item_code'], name='items_company_d63af2_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company', 'branch', 'item_name'], name='items_company_645a94_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='items_status_bc9bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company', 'branch', 'brand'], name='items_company_1c18e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('company', 'branch', 'item_name'), ('company', 'branch', 'barcode'), ('company', 'branch', 'item_code')},
        ),
    ]
