# Generated by Django 4.2.26 on 2026-03-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_stock_ledger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='stock_ledge_shop_id_4e6ddf_idx',
            old_name='stock_ledge_shop_id_0ebdbc_idx',
        ),
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='stock_ledge_movemen_0af00e_idx',
            old_name='stock_ledge_movemen_88fc32_idx',
        ),
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='stock_ledge_referen_f43b64_idx',
            old_name='stock_ledge_referen_a43814_idx',
        ),
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='stock_ledge_status_435f09_idx',
            old_name='stock_ledge_status_60333a_idx',
        ),
    ]
