# Generated by Django 4.2.26 on 2026-01-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_volume',
        ),
    ]
