# Generated by Django 4.2.26 on 2026-04-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_branch_unique_together_remove_branch_address_and_more'),
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='branch',
            field=models.ForeignKey(help_text='Associated branch', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='company.branch'),
        ),
    ]
