# Generated by Django 4.2.26 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_rename_stock_ledge_shop_id_0ebdbc_idx_stock_ledge_shop_id_4e6ddf_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockledger",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("OPENING_STOCK", "Opening Stock"),
                    ("PURCHASE", "Purchase"),
                    ("SALES_RETURN", "Sales Return"),
                    ("TRANSFER_IN", "Transfer In"),
                    ("ADJUSTMENT_IN", "Adjustment In"),
                    ("SALE", "Sale"),
                    ("PURCHASE_RETURN", "Purchase Return"),
                    ("TRANSFER_OUT", "Transfer Out"),
                    ("DAMAGE", "Damage"),
                    ("ADJUSTMENT_OUT", "Adjustment Out"),
                    ("SAMPLE_GIVEN", "Sample Given"),
                    ("INTERNAL_USE", "Internal Use"),
                    ("THEFT_LOSS", "Theft / Loss"),
                    ("DAMAGE_EXPIRED", "Damage / Expired"),
                ],
                max_length=30,
            ),
        ),
    ]
