# Generated by Django 4.2.27 on 2026-03-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('items', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sales_code', models.CharField(help_text='Unique sales number', max_length=50, unique=True)),
                ('sales_date', models.DateField(blank=True, help_text='Sales date', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal before tax', max_digits=12)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total tax amount', max_digits=12, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Discount percentage', max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total discount amount', max_digits=12, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final total amount', max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid', max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Pending amount', max_digits=12)),
                ('payment_mode', models.IntegerField(choices=[(1, 'Cash'), (2, 'UPI'), (3, 'Partial'), (4, 'Bank Transfer')], default=1, help_text='Payment method')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted, 3: Fully Returned')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='company.branch')),
                ('company', models.ForeignKey(help_text='Company', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='company.company')),
                ('party', models.ForeignKey(blank=True, help_text='Customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='settings.party')),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Due amount', max_digits=12)),
                ('date', models.DateField(blank=True, help_text='Entry date', null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text='Entry month (1-12)', null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Entry year (YYYY)', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_ledger_entries', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ledger_entries', to='company.company')),
                ('party', models.ForeignKey(help_text='Customer', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='settings.party')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='sales.sales')),
            ],
            options={
                'verbose_name': 'Customer Ledger',
                'verbose_name_plural': 'Customer Ledger',
                'db_table': 'customer_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item_quantity', models.DecimalField(decimal_places=2, default=1.0, help_text='Quantity sold', max_digits=10)),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity returned', max_digits=10)),
                ('item_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit at time of sale', max_digits=12)),
                ('item_description', models.CharField(help_text='Item Description', max_length=255)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount for this item', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax amount for this item', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount for this item', max_digits=12)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_transactions', to='company.branch')),
                ('company', models.ForeignKey(help_text='Company', on_delete=django.db.models.deletion.CASCADE, related_name='sales_transactions', to='company.company')),
                ('item', models.ForeignKey(help_text='Item sold', on_delete=django.db.models.deletion.CASCADE, related_name='sales_transactions', to='items.item')),
                ('sales', models.ForeignKey(help_text='Parent invoice', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.sales')),
            ],
            options={
                'verbose_name': 'Sales Transaction',
                'verbose_name_plural': 'Sales Transactions',
                'db_table': 'sales_transactions',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sales', 'item'], name='sales_trans_sales_i_9f0fa0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['party', 'status'], name='sales_party_i_e7bab9_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['sales_code'], name='sales_sales_c_b1fa30_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['payment_mode'], name='sales_payment_fb1eed_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['company', 'branch', 'sales_date'], name='sales_company_d2a974_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sales',
            unique_together={('company', 'branch', 'sales_code')},
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['company', 'branch', 'party', 'created_at'], name='customer_le_company_11697e_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['status'], name='customer_le_status_67721b_idx'),
        ),
    ]
