# Generated by Django 4.2.26 on 2026-03-30 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('settings', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='settings.party'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_ledger_entries', to='company.branch'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ledger_entries', to='company.company'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='party',
            field=models.ForeignKey(help_text='Customer', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='settings.party'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='sales.sales'),
        ),
        migrations.AddIndex(
            model_name='salestransaction',
            index=models.Index(fields=['sales', 'item'], name='sales_trans_sales_i_9f0fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['party', 'status'], name='sales_party_i_e7bab9_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['sales_code'], name='sales_sales_c_b1fa30_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['payment_mode'], name='sales_payment_fb1eed_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['company', 'branch', 'sales_date'], name='sales_company_d2a974_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sales',
            unique_together={('company', 'branch', 'sales_code')},
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['company', 'branch', 'party', 'created_at'], name='customer_le_company_11697e_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['status'], name='customer_le_status_67721b_idx'),
        ),
    ]
