# Generated by Django 4.2.26 on 2026-03-08 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_stock_ledge_shop_id_0ebdbc_idx_stock_ledge_shop_id_4e6ddf_idx_and_more'),
        ('sales', '0001_initial'),
        ('shops', '0005_alter_shop_city_alter_shop_country_alter_shop_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='is_reverted',
            field=models.BooleanField(default=False, help_text='True when full sales invoice is reverted'),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity returned', max_digits=10),
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('return_code', models.CharField(help_text='Unique sales return number', max_length=50, unique=True)),
                ('return_date', models.DateTimeField(auto_now_add=True, help_text='Return created time')),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total return amount', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Return notes', null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('sales', models.ForeignKey(help_text='Original sales invoice', on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sales')),
                ('shop', models.ForeignKey(help_text='Shop', on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Sales Return',
                'verbose_name_plural': 'Sales Returns',
                'db_table': 'sales_returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnTransaction',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('return_quantity', models.DecimalField(decimal_places=2, default=0.0, help_text='Returned quantity', max_digits=10)),
                ('item_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Item rate at sale time', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Return amount for this line', max_digits=12)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('item', models.ForeignKey(help_text='Returned item', on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_transactions', to='items.item')),
                ('sales_return', models.ForeignKey(help_text='Sales return header', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.salesreturn')),
                ('sales_transaction', models.ForeignKey(help_text='Original sales line', on_delete=django.db.models.deletion.CASCADE, related_name='return_transactions', to='sales.salestransaction')),
                ('shop', models.ForeignKey(help_text='Shop', on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_transactions', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Sales Return Transaction',
                'verbose_name_plural': 'Sales Return Transactions',
                'db_table': 'sales_return_transactions',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['shop', 'return_date'], name='sales_retur_shop_id_a88673_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['sales', 'status'], name='sales_retur_sales_i_132718_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['return_code'], name='sales_retur_return__ce1607_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesreturn',
            unique_together={('shop', 'return_code')},
        ),
        migrations.AddIndex(
            model_name='salesreturntransaction',
            index=models.Index(fields=['sales_return', 'item'], name='sales_retur_sales_r_74939e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturntransaction',
            index=models.Index(fields=['sales_transaction'], name='sales_retur_sales_t_64cf63_idx'),
        ),
    ]
