# Generated by Django 4.2.26 on 2026-02-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0005_alter_shop_city_alter_shop_country_alter_shop_state'),
        ('settings', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='settings.party'),
        ),
        migrations.AddField(
            model_name='sales',
            name='shop',
            field=models.ForeignKey(help_text='Shop', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='salestransaction',
            index=models.Index(fields=['sales', 'item'], name='sales_trans_sales_i_9f0fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['shop', 'sales_date'], name='sales_shop_id_5c7c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['party', 'status'], name='sales_party_i_e7bab9_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['sales_code'], name='sales_sales_c_b1fa30_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['payment_mode'], name='sales_payment_fb1eed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sales',
            unique_together={('shop', 'sales_code')},
        ),
    ]
