# Generated by Django 4.2.27 on 2026-04-10 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('settings', '0002_remove_party_wallet_balance'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('date', models.DateField(blank=True, help_text='Payment date', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='company.company')),
                ('party', models.ForeignKey(help_text='Customer', on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='settings.party')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment History',
                'db_table': 'payment_history',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'branch', 'party', 'date'], name='payment_his_company_415034_idx'), models.Index(fields=['status'], name='payment_his_status_4aff87_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('month', models.PositiveSmallIntegerField(help_text='Statement month (1-12)')),
                ('year', models.PositiveSmallIntegerField(help_text='Statement year (YYYY)')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('month_due_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('month_paid_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statements', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statements', to='company.company')),
                ('party', models.ForeignKey(help_text='Customer', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statements', to='settings.party')),
            ],
            options={
                'verbose_name': 'Monthly Statement',
                'verbose_name_plural': 'Monthly Statements',
                'db_table': 'monthly_statements',
                'ordering': ['-year', '-month', '-created_at'],
                'indexes': [models.Index(fields=['company', 'branch', 'party', 'year', 'month'], name='monthly_sta_company_51a282_idx'), models.Index(fields=['status'], name='monthly_sta_status_e75f07_idx')],
                'unique_together': {('company', 'branch', 'party', 'year', 'month')},
            },
        ),
    ]
