# Generated by Django 4.2.26 on 2026-03-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_returns_and_revert'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salesreturn',
            new_name='sales_retur_shop_id_3ced22_idx',
            old_name='sales_retur_shop_id_a88673_idx',
        ),
        migrations.RenameIndex(
            model_name='salesreturn',
            new_name='sales_retur_sales_i_53b512_idx',
            old_name='sales_retur_sales_i_132718_idx',
        ),
        migrations.RenameIndex(
            model_name='salesreturn',
            new_name='sales_retur_return__5549cd_idx',
            old_name='sales_retur_return__ce1607_idx',
        ),
        migrations.RenameIndex(
            model_name='salesreturntransaction',
            new_name='sales_retur_sales_r_7eb1ae_idx',
            old_name='sales_retur_sales_r_74939e_idx',
        ),
        migrations.RenameIndex(
            model_name='salesreturntransaction',
            new_name='sales_retur_sales_t_b66dbb_idx',
            old_name='sales_retur_sales_t_64cf63_idx',
        ),
    ]
