# Generated by Django 4.2.26 on 2026-03-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_rename_sales_retur_shop_id_a88673_idx_sales_retur_shop_id_3ced22_idx_and_more"),
        ("settings", "0002_add_current_balance"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="balance_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Pending amount",
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name="CustomerLedger",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, blank=True, null=True)),
                ("entry_type", models.CharField(choices=[("SALE", "Sale"), ("PAYMENT", "Payment"), ("RETURN", "Return"), ("ADJUSTMENT", "Adjustment")], max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, help_text="Positive for sale, negative for payment/return", max_digits=12)),
                ("balance_after", models.DecimalField(decimal_places=2, help_text="Balance after entry", max_digits=12)),
                ("reference_type", models.CharField(blank=True, max_length=50, null=True)),
                ("reference_id", models.IntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("status", models.IntegerField(default=0, help_text="0: Active, 1: Inactive, 2: Deleted")),
                ("party", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ledger_entries", to="settings.party")),
                ("sales", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ledger_entries", to="sales.sales")),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customer_ledger_entries", to="shops.shop")),
            ],
            options={
                "db_table": "customer_ledger",
                "verbose_name": "Customer Ledger",
                "verbose_name_plural": "Customer Ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customerledger",
            index=models.Index(fields=["shop", "party", "created_at"], name="customer_l_shop_id_0d4a23_idx"),
        ),
        migrations.AddIndex(
            model_name="customerledger",
            index=models.Index(fields=["entry_type", "created_at"], name="customer_l_entry_t_85c2df_idx"),
        ),
        migrations.AddIndex(
            model_name="customerledger",
            index=models.Index(fields=["reference_type", "reference_id"], name="customer_l_referen_9f0a6f_idx"),
        ),
        migrations.AddIndex(
            model_name="customerledger",
            index=models.Index(fields=["status"], name="customer_l_status_2f7b2c_idx"),
        ),
    ]
