# Generated by Django 4.2.26 on 2026-03-14 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_add_current_balance'),
        ('sales', '0004_add_balance_and_ledger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerledger',
            new_name='customer_le_shop_id_5e0852_idx',
            old_name='customer_l_shop_id_0d4a23_idx',
        ),
        migrations.RenameIndex(
            model_name='customerledger',
            new_name='customer_le_entry_t_cbb397_idx',
            old_name='customer_l_entry_t_85c2df_idx',
        ),
        migrations.RenameIndex(
            model_name='customerledger',
            new_name='customer_le_referen_575ccb_idx',
            old_name='customer_l_referen_9f0a6f_idx',
        ),
        migrations.RenameIndex(
            model_name='customerledger',
            new_name='customer_le_status_67721b_idx',
            old_name='customer_l_status_2f7b2c_idx',
        ),
        migrations.AlterField(
            model_name='customerledger',
            name='party',
            field=models.ForeignKey(help_text='Customer', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='settings.party'),
        ),
    ]
