# Generated by Django 4.2.26 on 2026-03-19 00:00

from django.db import migrations, models
from django.db.models.functions import ExtractMonth, ExtractYear, TruncDate


def backfill_entry_date_fields(apps, schema_editor):
    CustomerLedger = apps.get_model("sales", "CustomerLedger")
    CustomerLedger.objects.filter(date__isnull=True).update(
        date=TruncDate("created_at"),
        month=ExtractMonth("created_at"),
        year=ExtractYear("created_at"),
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_add_balance_and_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerledger",
            name="date",
            field=models.DateField(blank=True, help_text="Entry date", null=True),
        ),
        migrations.AddField(
            model_name="customerledger",
            name="month",
            field=models.PositiveSmallIntegerField(blank=True, help_text="Entry month (1-12)", null=True),
        ),
        migrations.AddField(
            model_name="customerledger",
            name="year",
            field=models.PositiveSmallIntegerField(blank=True, help_text="Entry year (YYYY)", null=True),
        ),
        migrations.RunPython(backfill_entry_date_fields, noop_reverse),
    ]
