# Generated by Codex on 2026-03-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_customer_l_shop_id_0d4a23_idx_customer_le_shop_id_5e0852_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sales',
            name='sales_shop_id_5c7c8f_idx',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sales_date',
        ),
    ]
