# Generated by Django 4.2.26 on 2026-03-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_date_month_year_to_customerledger'),
        ('sales', '0006_remove_sales_sales_date'),
    ]

    operations = [
    ]
