# Generated by Codex on 2026-03-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_merge_20260319_0346"),
        (
            "sales",
            "0005_rename_customer_l_shop_id_0d4a23_idx_customer_le_shop_id_5e0852_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customerledger",
            name="customer_le_entry_t_cbb397_idx",
        ),
        migrations.RemoveIndex(
            model_name="customerledger",
            name="customer_le_referen_575ccb_idx",
        ),
        migrations.RemoveField(
            model_name="customerledger",
            name="balance_after",
        ),
        migrations.RemoveField(
            model_name="customerledger",
            name="entry_type",
        ),
        migrations.RemoveField(
            model_name="customerledger",
            name="reference_id",
        ),
        migrations.RemoveField(
            model_name="customerledger",
            name="reference_type",
        ),
    ]
