# Generated by Django 4.2.26 on 2026-03-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_customerledger_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Due amount', max_digits=12),
        ),
    ]
