# Generated by Codex on 2026-03-23

from django.db import migrations, models
from django.db.models.functions import TruncDate


def backfill_sales_date(apps, schema_editor):
    Sales = apps.get_model("sales", "Sales")
    Sales.objects.filter(sales_date__isnull=True).update(
        sales_date=TruncDate("created_at")
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_alter_customerledger_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="sales_date",
            field=models.DateField(blank=True, help_text="Sales date", null=True),
        ),
        migrations.AddIndex(
            model_name="sales",
            index=models.Index(fields=["shop", "sales_date"], name="sales_shop_sales_date_idx"),
        ),
        migrations.RunPython(backfill_sales_date, noop_reverse),
    ]
