# Generated by Django 4.2.26 on 2026-03-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_add_sales_date'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sales',
            new_name='sales_shop_id_5c7c8f_idx',
            old_name='sales_shop_sales_date_idx',
        ),
    ]
