# Generated by Django 4.2.26 on 2026-01-23 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),

    ]

    operations = [
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('menu_name', models.CharField(max_length=100, unique=True)),
                ('cust_menu_name', models.CharField(help_text='Customized Menu Name For Parties', max_length=100, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('menu_icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('menu_url', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
            ],
            options={
                'verbose_name': 'Menu Master',
                'verbose_name_plural': 'Menu Masters',
                'db_table': 'menu_master',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('otp_type', models.CharField(choices=[('REGISTRATION', 'Registration'), ('LOGIN', 'Login')], default='LOGIN', help_text='Purpose of OTP', max_length=50)),
                ('attempts', models.IntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, help_text='User blocked from OTP service until this time', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether OTP has been verified')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'db_table': 'otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', '-created_at'], name='otps_phone_n_a0c674_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuModuleMaster',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('module_name', models.CharField(max_length=100, unique=True)),
                ('cust_module_name', models.CharField(help_text='Customized Module Name For Parties', max_length=100, unique=True)),
                ('module_url', models.TextField(blank=True, null=True)),
                ('module_description', models.TextField(blank=True, null=True)),
                ('module_permission_type_ids', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('module_icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('module_visibility', models.IntegerField(default=1, help_text='1: Yes, 2: No')),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='accounts.menumaster')),
            ],
            options={
                'verbose_name': 'Menu Module Master',
                'verbose_name_plural': 'Menu Module Masters',
                'db_table': 'menu_module_master',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user_lock', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),

                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
