# Generated by Django 4.2.26 on 2025-12-07 17:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_password'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('LOGIN', 'Login')], default='LOGIN', help_text='Purpose of OTP', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='List of permissions user has access to'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_staff', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='user',
            name='shops',
            field=models.ManyToManyField(blank=True, help_text='The shops this user has access to', related_name='staff', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='attempts',
            field=models.IntegerField(default=0, help_text='Number of verification attempts'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='OTP expiration time', null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether OTP has been verified'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='max_attempts',
            field=models.IntegerField(default=3, help_text='Maximum number of verification attempts'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(help_text='6-digit OTP code', max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_secret',
            field=models.CharField(blank=True, help_text='Secret key for OTP generation', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(max_length=150)),
                ('permissions', models.JSONField(blank=True, default=list, help_text='List of permissions user has access to')),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.rolepermission'),
        ),
    ]
