# Generated by Django 4.2.26 on 2026-01-23 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_shop_id'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_staff', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='user',
            name='shops',
            field=models.ManyToManyField(blank=True, help_text='The shops this user has access to', related_name='staff', to='shops.shop'),
        ),
    ]
