# Generated by Django 4.2.26 on 2026-03-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='companies',
        ),
    ]
