# Generated by Django 4.2.26 on 2025-12-29 21:40

from django.db import migrations
from django.contrib.auth.hashers import make_password


def fix_null_passwords(apps, schema_editor):
    """Set default password for users with null/empty passwords"""
    User = apps.get_model('accounts', 'User')
    
    # Update all users with null or empty passwords
    users_with_null_password = User.objects.filter(password__isnull=True) | User.objects.filter(password='')
    count = users_with_null_password.count()
    
    if count > 0:
        users_with_null_password.update(password=make_password('admin123'))
        print(f"Fixed passwords for {count} users")


def reverse_fix_null_passwords(apps, schema_editor):
    """Reverse function - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(fix_null_passwords, reverse_fix_null_passwords),
    ]
