# Generated by Django 4.2.26 on 2025-12-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_email_otp_otp_type_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='otp_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='otp',
            name='blocked_until',
            field=models.DateTimeField(blank=True, help_text='User blocked from OTP service until this time', null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='max_requests',
            field=models.IntegerField(default=3, help_text='Maximum OTP requests before blocking'),
        ),
        migrations.AddField(
            model_name='otp',
            name='request_count',
            field=models.IntegerField(default=0, help_text='Number of OTP requests made'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='attempts',
            field=models.IntegerField(default=0, help_text='Number of OTP verification attempts'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='max_attempts',
            field=models.IntegerField(default=3, help_text='Maximum allowed verification attempts'),
        ),
    ]
