# Generated by Django 4.2.26 on 2026-03-31 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branches',
        ),
    ]
