# Generated by Django 4.2.26 on 2026-01-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_city_alter_user_country_alter_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, blank=True, null=True, unique=True),
        ),
    ]
