# Generated by Django 4.2.26 on 2026-01-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fix_existing_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumaster',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='menumaster',
            name='user',
        ),
        migrations.RemoveField(
            model_name='menumodulemaster',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='menumodulemaster',
            name='user',
        ),
        migrations.AlterField(
            model_name='menumaster',
            name='cust_menu_name',
            field=models.CharField(help_text='Customized Menu Name For Parties', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='menumaster',
            name='menu_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='menumodulemaster',
            name='cust_module_name',
            field=models.CharField(help_text='Customized Module Name For Parties', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='menumodulemaster',
            name='module_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
