# Generated by Django 4.2.26 on 2025-12-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_otp_otp_secret_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='max_requests',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='request_count',
        ),
    ]
