# Generated by Django 4.2.26 on 2026-02-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_increase_phone_number_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodulemaster',
            name='menu',
        ),
        migrations.DeleteModel(
            name='MenuMaster',
        ),
        migrations.DeleteModel(
            name='MenuModuleMaster',
        ),
    ]
