# Generated by Django 4.2.26 on 2025-12-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_otp_expires_at_remove_otp_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether OTP has been verified'),
        ),
    ]
