# Generated by Django 4.2.26 on 2026-04-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
    ]
