# Generated by Django 4.2.26 on 2025-12-18 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_name', models.CharField(max_length=100)),
                ('cust_menu_name', models.CharField(help_text='Customized Menu Name For Parties', max_length=100)),
                ('priority', models.IntegerField(default=0)),
                ('menu_icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('menu_url', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
            ],
            options={
                'verbose_name': 'Menu Master',
                'verbose_name_plural': 'Menu Masters',
                'db_table': 'menu_master',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuModuleMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_name', models.CharField(max_length=100)),
                ('cust_module_name', models.CharField(help_text='Customized Module Name For Parties', max_length=100)),
                ('module_url', models.TextField(blank=True, null=True)),
                ('module_description', models.TextField(blank=True, null=True)),
                ('module_permission_type_ids', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('module_icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('module_visibility', models.IntegerField(default=1, help_text='1: Yes, 2: No')),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='accounts.menumaster')),
            ],
            options={
                'verbose_name': 'Menu Module Master',
                'verbose_name_plural': 'Menu Module Masters',
                'db_table': 'menu_module_master',
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
