# Generated by Django 4.2.26 on 2025-12-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_menumaster_menumodulemaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='email',
        ),
        migrations.AlterField(
            model_name='otp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
