# Generated by Django 4.2.26 on 2025-12-27 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shop_business_type_id_alter_shop_email'),
        ('accounts', '0009_remove_otp_email_alter_otp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumaster',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_menus', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='menumaster',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_menus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menumodulemaster',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_modules', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='menumodulemaster',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
