# Generated by Django 4.2.26 on 2026-01-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SOFT_DELETE', 'Soft Delete')], max_length=20)),
                ('entity_name', models.CharField(help_text='Model name that was affected', max_length=100)),
                ('record_id', models.IntegerField(help_text='ID of the affected record')),
                ('user_id', models.IntegerField(blank=True, help_text='User who performed the action', null=True)),
                ('shop_id', models.IntegerField(blank=True, help_text='Shop where action was performed', null=True)),
                ('old_data', models.JSONField(blank=True, help_text='Previous state of the record', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='New state of the record', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_name', 'record_id'], name='audit_logs_entity__fab5b9_idx'), models.Index(fields=['user_id', 'created_at'], name='audit_logs_user_id_fbfd51_idx'), models.Index(fields=['shop_id', 'created_at'], name='audit_logs_shop_id_db6c42_idx'), models.Index(fields=['action_type', 'created_at'], name='audit_logs_action__94af82_idx')],
            },
        ),
    ]
