# Generated by Django 4.2.26 on 2026-01-12 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Party name', max_length=255)),
                ('party_type', models.IntegerField(choices=[(1, 'Customer'), (2, 'Vendor'), (3, 'Both')], default=1, help_text='1: Customer, 2: Vendor, 3: Both')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance', max_digits=10)),
                ('balance_type', models.IntegerField(blank=True, choices=[(1, 'Debit (Receivable)'), (2, 'Credit (Payable/Advance)')], help_text='1: Debit (Receivable), 2: Credit (Payable/Advance)', null=True)),
                ('customer_category', models.IntegerField(blank=True, choices=[(1, 'Regular'), (2, 'Card Holder'), (3, 'Vara (Home Delivery)')], help_text='1: Regular, 2: Card Holder, 3: Vara (Home Delivery)', null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
                ('shop', models.ForeignKey(help_text='Associated shop', on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='shops.shop')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'db_table': 'parties',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'party_type'], name='parties_shop_id_26a551_idx'), models.Index(fields=['phone_number'], name='parties_phone_n_447d92_idx'), models.Index(fields=['email'], name='parties_email_fe65c4_idx')],
            },
        ),
    ]
