# Generated by Django 4.2.26 on 2026-01-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='party',
            name='parties_shop_id_e0dcf3_idx',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='shop_id',
            new_name='shop',
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['shop', 'party_type'], name='parties_shop_id_26a551_idx'),
        ),
    ]
