# Generated by Django 4.2.26 on 2026-02-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_shop_city_alter_shop_country_alter_shop_state'),
        ('parties', '0002_remove_party_parties_shop_id_e0dcf3_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('shop', 'name', 'phone_number', 'email')},
        ),
    ]
