# Generated by Django 4.2.26 on 2026-02-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_shop_city_alter_shop_country_alter_shop_state'),
        ('parties', '0003_alter_party_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('shop', 'email'), ('shop', 'phone_number'), ('shop', 'name')},
        ),
    ]
