# Generated by Django 4.2.26 on 2025-12-29 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_code', models.CharField(max_length=150, unique=True)),
                ('shop_name', models.CharField(max_length=150)),
                ('legal_name', models.CharField(max_length=150)),
                ('business_type_id', models.IntegerField(blank=True, default=0, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('tax_no', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='shop_logos')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('default_shop', models.IntegerField(default=0, help_text='0:No, 1:Yes')),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='cities_light.country')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_shops', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='cities_light.region')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'db_table': 'shops',
                'ordering': ['-created_at'],
            },
        ),
    ]
