# Generated by Django 4.2.26 on 2025-12-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
