# Generated by Django 4.2.26 on 2025-12-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='mobile_no',
            new_name='phone_number',
        ),
    ]
