# Generated by Django 4.2.26 on 2026-01-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_created_at_alter_shop_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
