# Generated by Django 4.2.26 on 2025-12-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_rename_mobile_no_to_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='default_shop',
            field=models.IntegerField(default=0, help_text='0:No, 1:Yes'),
        ),
    ]
