# Generated by Django 4.2.26 on 2025-12-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_shop_default_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
