# Generated by Django 4.2.26 on 2026-01-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('shops', '0004_alter_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='core.citymaster'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='core.countrymaster'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='core.statemaster'),
        ),
    ]
