# Generated by Django 4.2.26 on 2026-04-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('branch_name', 'company')},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='email',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='phone_number',
        ),
    ]
