# Generated by Django 4.2.26 on 2026-04-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_branch_unique_together_remove_branch_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_type_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Retail / Shops'), (2, 'Wholesale / Distribution'), (3, 'E-commerce / Online Selling'), (4, 'Manufacturing'), (5, 'Trading'), (6, 'Export / Import'), (7, 'Services / Consulting'), (8, 'IT & Software'), (9, 'Construction / Real Estate'), (10, 'Healthcare / Medical / Pharma'), (11, 'Transport & Logistics'), (12, 'Agriculture'), (13, 'Others')], default=0, null=True),
        ),
    ]
