# Generated by Django 4.2.26 on 2026-02-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0005_alter_shop_city_alter_shop_country_alter_shop_state'),
        ('core', '0002_add_country_timestamp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Party name', max_length=255)),
                ('party_type', models.IntegerField(choices=[(1, 'Customer'), (2, 'Vendor'), (3, 'Both')], default=1, help_text='1: Customer, 2: Vendor, 3: Both')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance', max_digits=10)),
                ('balance_type', models.IntegerField(blank=True, choices=[(1, 'Debit (Receivable)'), (2, 'Credit (Payable/Advance)')], help_text='1: Debit (Receivable), 2: Credit (Payable/Advance)', null=True)),
                ('customer_category', models.IntegerField(blank=True, choices=[(1, 'Regular'), (2, 'Card Holder'), (3, 'Vara (Home Delivery)')], help_text='1: Regular, 2: Card Holder, 3: Vara (Home Delivery)', null=True)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.citymaster')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.countrymaster')),
                ('shop', models.ForeignKey(help_text='Associated shop', on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='shops.shop')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.statemaster')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'db_table': 'parties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('brand_name', models.CharField(help_text='Brand name', max_length=150)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('shop', models.ForeignKey(help_text='Associated shop', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tax_name', models.CharField(help_text='Tax name', max_length=150, unique=True)),
                ('tax_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax value/percentage', max_digits=5)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('shop', models.ForeignKey(help_text='Associated shop', on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
                'db_table': 'taxes',
                'ordering': ['tax_name'],
                'indexes': [models.Index(fields=['shop', 'tax_name'], name='taxes_shop_id_72507c_idx'), models.Index(fields=['status'], name='taxes_status_520ed5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.CheckConstraint(check=models.Q(('tax_name', ''), _negated=True), name='tax_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.CheckConstraint(check=models.Q(('tax_value__gte', 0)), name='tax_value_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together={('shop', 'tax_name')},
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['shop', 'party_type'], name='parties_shop_id_26a551_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['phone_number'], name='parties_phone_n_447d92_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['email'], name='parties_email_fe65c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('shop', 'email'), ('shop', 'name'), ('shop', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['shop', 'brand_name'], name='brands_shop_id_71636a_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['status'], name='brands_status_28bd17_idx'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.CheckConstraint(check=models.Q(('brand_name', ''), _negated=True), name='brand_name_not_empty'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('shop', 'brand_name')},
        ),
    ]
