# Generated by Django 4.2.26 on 2026-02-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0005_alter_shop_city_alter_shop_country_alter_shop_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('brand_name', models.CharField(help_text='Brand name', max_length=150)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('shop', models.ForeignKey(help_text='Associated shop', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tax_name', models.CharField(help_text='Tax name', max_length=150, unique=True)),
                ('tax_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax value/percentage', max_digits=5)),
                ('status', models.IntegerField(default=0, help_text='0: Active, 1: Inactive, 2: Deleted')),
                ('shop', models.ForeignKey(help_text='Associated shop', on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
                'db_table': 'taxes',
                'ordering': ['tax_name'],
                'indexes': [models.Index(fields=['shop', 'tax_name'], name='taxes_shop_id_72507c_idx'), models.Index(fields=['status'], name='taxes_status_520ed5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.CheckConstraint(check=models.Q(('tax_name', ''), _negated=True), name='tax_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.CheckConstraint(check=models.Q(('tax_value__gte', 0)), name='tax_value_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together={('shop', 'tax_name')},
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['shop', 'brand_name'], name='brands_shop_id_71636a_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['status'], name='brands_status_28bd17_idx'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.CheckConstraint(check=models.Q(('brand_name', ''), _negated=True), name='brand_name_not_empty'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('shop', 'brand_name')},
        ),
    ]
