# Generated by Django 4.2.26 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Current outstanding balance",
                max_digits=12,
            ),
        ),
    ]
