# Generated by Django 4.2.27 on 2026-04-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='wallet_balance',
        ),
    ]
