# Generated by Django 4.2.26 on 2026-03-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_add_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='balance_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Debit (Pending/Receivable)'), (2, 'Credit (Advance/Payable)')], help_text='1: Debit (Receivable), 2: Credit (Payable/Advance)', null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pending or advance amount (absolute)', max_digits=10),
        ),
    ]
